# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Screen_Recorder.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Screen_Recorder(object):
    def setupUi(self, Screen_Recorder):
        Screen_Recorder.setObjectName("Screen_Recorder")
        Screen_Recorder.resize(495, 350)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("free-video-icon-818-thumb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Screen_Recorder.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Screen_Recorder)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 495, 350))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("recording-gif.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 290, 107, 34))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background:white;\n"
"color:black;\n"
"font-size:14px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(197, 290, 107, 34))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background:white;\n"
"color:black;\n"
"font-size:14px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(322, 290, 107, 34))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background:white;\n"
"color:black;\n"
"font-size:14px;")
        self.pushButton_3.setObjectName("pushButton_3")
        Screen_Recorder.setCentralWidget(self.centralwidget)

        self.retranslateUi(Screen_Recorder)
        QtCore.QMetaObject.connectSlotsByName(Screen_Recorder)

    def retranslateUi(self, Screen_Recorder):
        _translate = QtCore.QCoreApplication.translate
        Screen_Recorder.setWindowTitle(_translate("Screen_Recorder", "Recorder"))
        self.pushButton.setText(_translate("Screen_Recorder", "Start"))
        self.pushButton_2.setText(_translate("Screen_Recorder", "Stop"))
        self.pushButton_3.setText(_translate("Screen_Recorder", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Screen_Recorder = QtWidgets.QMainWindow()
    ui = Ui_Screen_Recorder()
    ui.setupUi(Screen_Recorder)
    Screen_Recorder.show()
    sys.exit(app.exec_())
